# Generated by Django 4.2.7 on 2023-12-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0012_complaint_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='willa',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotment', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='roomallotment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to=settings.AUTH_USER_MODEL),
        ),
    ]
