# Generated by Django 4.2.7 on 2023-12-26 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0013_roomallotment_delete_willa_remove_room_room_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='room',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='allotment', to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to=settings.AUTH_USER_MODEL),
        ),
    ]
