# Generated by Django 4.2.7 on 2023-12-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0014_alter_roomallotment_room_alter_roomallotment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room'),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
