# Generated by Django 4.2.7 on 2023-12-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_alter_roomallotment_room_alter_roomallotment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=2),
        ),
    ]
