# Generated by Django 4.2.7 on 2023-12-27 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_alter_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallotment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
