# Generated by Django 4.2.7 on 2023-12-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_roomallotment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomallotment',
            name='uid',
        ),
    ]
