# Generated by Django 4.2.7 on 2023-12-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('additional_info', models.BooleanField(default=False)),
            ],
        ),
    ]
