# Generated by Django 4.2.7 on 2023-12-30 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0021_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attentance', to=settings.AUTH_USER_MODEL),
        ),
    ]
