# Generated by Django 4.2.7 on 2023-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_remove_attendance_user_name_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
