# Generated by Django 4.2.7 on 2024-01-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0025_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.attendance'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='fee',
            field=models.IntegerField(max_length=5),
        ),
    ]
