# Generated by Django 4.2.7 on 2024-01-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0035_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
